feat!: level-aware content highlighting
vigoux/notifier.nvim pull request #24
Opened 2022-12-01 14:32 UTC by williamboman

I've been running a feature branch for a while now where this is one of the
added features. Figured it'd be really nice to be able to discern the severity
of a log item from its log level. This is a breaking change in terms of the
configuration schema where HL_CONTENT now is a table instead of a string.

2022-12-01 14:35 UTC, williamboman commented on teal/notifier/status.tl
> -      api.nvim_buf_add_highlight(StatusModule.buf_nr, cfg.NS_ID, hl_group, i - 1, 0, title_start_offset - 1)
Honestly not quite sure why this was needed (`- 1` to `+ 1`). Without this the content highlight doesn't cover the full text if the text is laid out on multiple rows. Now as I'm writing this out I'm not sure if this is the kind of thing where the offset need to be adjusted by the amount of rows, instead of being a hardcoded value (I only tested 2 rows at most).

2022-12-01 14:37 UTC, williamboman commented on teal/notifier/status.tl
> -      api.nvim_buf_add_highlight(StatusModule.buf_nr, cfg.NS_ID, hl_group, i - 1, 0, title_start_offset - 1)
Nope seems fine (I haven't bothered going through the logic of this so I don't fully understand why it's needed).

Before:
![Screenshot 2022-12-01 at 15 36 28](https://user-images.githubusercontent.com/6705160/205080307-78abee7b-5221-4f8f-99a8-c36e215ea294.png)


After:
![Screenshot 2022-12-01 at 15 35 53](https://user-images.githubusercontent.com/6705160/205080297-98384ac7-a912-4600-ba8e-e7b5fad81243.png)

2023-01-13 08:38 UTC, vigoux requested changes
Hi and sorry for the huge delay,
So it overall looks really great, but my (fairly minor) nitpick is the fact that this is a breaking change from the config POV.

Do you think you can add some logic in the `setup` function to detect the fact that the passed configuration is not a parameter ?

Thank you very much for that !

2023-01-28 14:30 UTC, williamboman commented
> Do you think you can add some logic in the `setup` function to detect the fact that the passed configuration is not a parameter ?

Sure! I expanded the config type to be `string|{integer:string}`, wdyt?

2023-01-30 10:58 UTC, vigoux commented
> Sure! I expanded the config type to be `string|{integer:string}`, wdyt?

Seems great !

2023-01-30 10:59 UTC, vigoux requested changes
Awesome, it now only needs a tiny bit of documentation. Do you think you can add it within this PR or do you want me to do it ?

2023-03-14 11:00 UTC, williamboman commented
Hey @vigoux sorry for the slow responses haha. The reason why is that I've actually stopped using this plugin for now, I realized that I prefer the old-school message mechanism for notifications.

2024-01-04 18:46 UTC, closed without merging